
import datetime, hashlib, hmac, json, logging, math, os, sys, time
import urllib.error, urllib.parse, urllib.request
from typing import Dict, List, Optional, Tuple

try:
    from dotenv import load_dotenv; load_dotenv()
except ImportError:
    pass

UTC = datetime.timezone.utc

MEXC_KEY    = os.getenv("MEXC")
MEXC_SECRET = os.getenv("MEXCSECRET")
MEXC_BASE   = "https://api.mexc.co"

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s")
log = logging.getLogger()
specs: Dict[str, Dict] = {}

# ── coin config ───────────────────────────────────────────────────────────────
def _coin_cfg(coin: str) -> Dict[str, str]:
    """Map any coin symbol to its Binance and MEXC futures identifiers."""
    c = coin.upper()
    return {"binance": f"{c}USDT", "mexc": f"{c}_USDT"}

LEVERAGE = 10
SYMBOL = ""; SYM = ""; AMT_USD = 10.0


# ── http ──────────────────────────────────────────────────────────────────────
def _get(url: str):
    with urllib.request.urlopen(url, timeout=10) as r:
        return json.loads(r.read())

def _http(method: str, url: str, headers=None, data=None, params=None):
    if params:
        url += "?" + urllib.parse.urlencode(sorted(params.items()))
    req = urllib.request.Request(url, data=data, headers=headers or {}, method=method)
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            body = r.read()
    except urllib.error.HTTPError as e:
        body = e.read()
    return json.loads(body) if body.strip() else {}

# ── MEXC auth ─────────────────────────────────────────────────────────────────
def mexc(method: str, endpoint: str, params=None, body=None):
    params = params or {}
    ts  = str(int(time.time() * 1000))
    sp  = ("&".join(f"{k}={v}" for k, v in sorted(params.items()))
           if method == "GET"
           else (json.dumps(body, separators=(",", ":"), sort_keys=True) if body else ""))
    sig = hmac.new(MEXC_SECRET.encode(), (MEXC_KEY + ts + sp).encode(), hashlib.sha256).hexdigest()
    hdr = {"ApiKey": MEXC_KEY, "Request-Time": ts, "Signature": sig,
           "Content-Type": "application/json", "Accept": "application/json"}
    raw = (json.dumps(body, separators=(",", ":"), sort_keys=True).encode()
           if body and method not in ("GET", "DELETE") else None)
    try:
        return _http(method, MEXC_BASE + endpoint, headers=hdr, data=raw,
                     params=params if method in ("GET", "DELETE") else None)
    except Exception as e:
        log.error(f"mexc {method} {endpoint}: {e}"); return {}

# ── specs / sizing ────────────────────────────────────────────────────────────
def load_specs():
    rows = mexc("GET", "/api/v1/contract/detail").get("data") or []
    for c in rows:
        s  = c["symbol"].upper()
        vu = float(c.get("volUnit", 1))
        pu = float(c.get("priceUnit", 0.5))
        cs = float(c.get("contractSize", vu))
        raw = f"{vu:.10f}".rstrip("0")
        p   = len(raw.split(".")[1]) if "." in raw else 0
        specs[s] = {"p": p, "t": pu, "vu": vu, "cs": cs}
    log.info(f"specs: {len(specs)} contracts  {SYM}={specs.get(SYM)}")

def _tick():  return specs.get(SYM, {}).get("t", 0.5)
def _prec():  return specs.get(SYM, {}).get("p", 0)
def _mos():   return specs.get(SYM, {}).get("vu", 1.0)

def _rfmt_price(v: float) -> str:
    t = _tick(); r = round(v / t) * t
    s = f"{t:.10f}".rstrip("0")
    dec = len(s.split(".")[1]) if "." in s else 0
    return f"{r:.{dec}f}"

def _rfmt_vol(v: float) -> str:
    p = _prec()
    if p >= 0: return f"{round(v, p):.{p}f}"
    d = 10 ** abs(p); return str(int(round(v / d) * d))

def _contracts(mark: float) -> float:
    cs = specs.get(SYM, {}).get("cs", 1.0)
    return float(_rfmt_vol(max(0, AMT_USD / (cs * mark))))

# ── orders ────────────────────────────────────────────────────────────────────
# Hedge / dual-side mode (positionMode=1): long and short tracked separately.
# positionMode is sent per-order per the MEXC docs.
#
# MEXC futures sides (hedge mode):
#   1 = open long    3 = open short
#   4 = close long   2 = close short
#
# openType: 1 = isolated margin, 2 = cross margin

_POSITION_MODE = 1   # 1=hedge/dual-side  2=one-way
_OPEN_TYPE     = 1   # 1=isolated  2=cross

def _open_ids() -> set:
    data = mexc("GET", "/api/v1/private/order/list/open_orders",
                params={"symbol": SYM, "page_num": 1, "page_size": 50}).get("data") or []
    if isinstance(data, dict): data = data.get("resultList", [])
    return {str(o.get("orderId", o.get("id", ""))) for o in data}

def place_limit_order(direction: int, mark: float) -> Optional[str]:
    """
    Open a position in hedge/dual-side mode.
    direction: +1 = open long  (side=1)
               -1 = open short (side=3)
    """
    vol = _contracts(mark)
    if vol < _mos():
        log.warning(f"size {vol} < min {_mos()} — skipped"); return None
    side = 1 if direction == 1 else 3   # MEXC: 1=open-long, 3=open-short
    body = {"symbol":       SYM,
            "price":        _rfmt_price(mark),
            "vol":          _rfmt_vol(vol),
            "leverage":     LEVERAGE,
            "side":         side,
            "type":         1,               # limit
            "openType":     _OPEN_TYPE,      # 1=isolated, 2=cross
            "positionMode": 2} #_POSITION_MODE}  # 1=hedge, 2=one-way
    r = mexc("POST", "/api/v1/private/order/create", body=body)
    if not r.get("success"):
        log.error(f"order rejected: {r}"); return None
    oid = str(r.get("data", ""))
    label = "LONG" if direction == 1 else "SHORT"
    log.info(f"  open {label} {_rfmt_vol(vol)} @ {_rfmt_price(mark)}  id={oid}")
    return oid

def close_position(direction: int, mark: float) -> Optional[str]:
    """
    Close an open position in hedge/dual-side mode.
    direction of the position to close: +1 = close long  (side=4)
                                        -1 = close short (side=2)
    """
    vol = _contracts(mark)
    if vol < _mos():
        log.warning(f"close size {vol} < min {_mos()} — skipped"); return None
    side = 4 if direction == 1 else 2   # MEXC: 4=close-long, 2=close-short
    body = {"symbol":       SYM,
            "price":        _rfmt_price(mark),
            "vol":          _rfmt_vol(vol),
            "leverage":     LEVERAGE,
            "side":         side,
            "type":         1,               # limit
            "openType":     _OPEN_TYPE,
            "positionMode": _POSITION_MODE}
    r = mexc("POST", "/api/v1/private/order/create", body=body)
    if not r.get("success"):
        log.error(f"close order rejected: {r}"); return None
    oid = str(r.get("data", ""))
    label = "LONG" if direction == 1 else "SHORT"
    log.info(f"  close {label} {_rfmt_vol(vol)} @ {_rfmt_price(mark)}  id={oid}")
    return oid


    r = mexc("DELETE", "/api/v1/private/order/cancel",
             params={"symbol": SYM, "orderId": oid})
    log.info(f"  cancel {oid}: {r}")

def is_filled(oid: str) -> bool:
    return oid not in _open_ids()

def get_mark() -> float:
    d = mexc("GET", "/api/v1/contract/ticker", params={"symbol": SYM}).get("data") or {}
    return float(d.get("fairPrice", d.get("lastPrice", 0)) or 0)

def get_position() -> Tuple[int, float]:
    """Return (direction, usd_size): direction +1 long / -1 short / 0 flat,
    usd_size = contracts * contractSize * markPrice (0.0 when flat).
    Logs the raw response on first call so field names can be verified."""
    raw = mexc("GET", "/api/v1/private/position/open_positions",
               params={"symbol": SYM})
    log.info(f"  position raw: {json.dumps(raw)[:400]}")
    data = raw.get("data") or []
    if isinstance(data, dict):
        data = data.get("resultList", [])
    if not data:
        return 0, 0.0
    for p in data:
        sym = str(p.get("symbol", "")).upper()
        if sym != SYM:
            continue
        # MEXC futures uses holdVol = number of contracts held
        hold = float(p.get("holdVol") or p.get("holdVolume") or 0)
        if hold <= 0:
            continue
        pos_type  = int(p.get("positionType", 1))   # 1=long, 2=short
        direction = 1 if pos_type == 1 else -1
        # holdAvgPrice is the confirmed field from MEXC response              mp = (float(p.get("holdAvgPrice") or 0)                                     or float(p.get("openAvgPrice") or 0)                                  or float(p.get("markPrice") or 0)                                     or get_mark())
        cs  = specs.get(SYM, {}).get("cs", 1.0)                               usd = hold * cs * mp                                                  log.info(f"  position parsed: sym={sym} hold={hold} posType={pos_type} "                                                                             f"mp={mp:.4f} cs={cs} usd=${usd:.2f}")                       return direction, usd                                             return 0, 0.0                                                                                                                           # ── Binance candles ───────────────────────────────────────────────────────────                                                            _BBASE = "https://api.binance.com/api/v3/klines"                      
                                                                                                                                                                                                                                                                                                                                                                                                                                    def compute_signals(bars: List[Dict]) -> Tuple[List[int], List[int], List[float], List[Dict]]:                                                  """                                                                   Returns (labels, oscillator, equity, signal_events).                                                                                        oscillator[i]: +1 long, -1 short, 0 flat
    equity[i]:     cumulative strategy equity starting at 1.0                                                                                   Signal logic (strict):                                                  1. EXIT DIRECTION: when leaving a cluster (label > 0 → different label),                                                                       the exit direction is determined by the price move away from the cluster                                                                    (bar[i+1].close > bar[i].close → +1, else -1).                                                                                           2. ENTRY DIRECTION: each cluster remembers the direction it was entered                                                                        the FIRST time (price move INTO the cluster on its first visit).                                                                            Every subsequent re-entry of that same cluster replays the same                                                                             entry direction — no recalculation.                                                                                                      3. RACE CONDITION: if a cluster exit leads directly into another cluster                                                                       (next_label > 0 and has a stored entry_dir), the entry direction of                                                                         the destination cluster wins over the exit direction.                                                                                    4. Noise bars (label == 0) never fire signals but do not reset position.                                                                                                                                        signal_events keys:                                                       bar        – bar index where the signal fired                         kind       – "exit" | "entry_win" (race-condition entry beat exit)                                                                          final_dir  – the direction applied (+1 / -1)                          dissolved  – True if immediately re-absorbed (next bar same cluster)                                                                    """                                                                   if not bars:                                                              return [], [], [], []
                                                                          # normalise (time_index, close) to [0,1]²                             n     = len(bars)                                                     t0    = bars[0]["t"]                                                  t_max = bars[-1]["t"] - t0 or 1                                       p_min = min(b["l"] for b in bars)                                     p_max = max(b["h"] for b in bars)                                     p_rng = p_max - p_min or 1.0                                                                                                                scaled = [((b["t"] - t0) / t_max,                                                (b["c"]  - p_min) / p_rng)                                           for b in bars]
                                                                          labels = _dbscan(scaled, DBSCAN_EPS, DBSCAN_MIN_PTS)                                                                                        # ── pass 1: single forward walk — build entry_dir map and emit signals ────                                                                #                                                                     # entry_dir[cluster_id] = the signal direction that was HELD when this                                                                      # cluster was first entered. That is: the exit_direction fired by whatever                                                                  # cluster (or noise transition) came before, at the moment of first arrival.
    #                                                                     # Rule summary:                                                       #   - Leaving a real cluster fires exit_direction (+1/-1 from price move).                                                                  #   - If the destination cluster already has entry_dir stored (re-entry or                                                                  #     race condition), entry_dir wins over exit_direction.            #   - The winning direction is stored as entry_dir for any NEW destination                                                                  #     cluster (first visit).                                          #   - Every re-entry of a cluster (regardless of source) replays entry_dir.
                                                                          entry_dir:  Dict[int, int] = {}   # cluster_id → direction held on first entry                                                              signal_events: List[Dict] = []                                        event_map:  Dict[int, int] = {}   # bar_index → final_dir for oscillator                                                                                                                                          current_dir: int = 0   # direction currently held as we walk forward                                                                                                                                              for i in range(n - 1):                                                    cur_lbl  = labels[i]
        next_lbl = labels[i + 1]                                                                                                                    # ── only act on transitions out of a real cluster ──────────────────                                                                       if cur_lbl <= 0 or next_lbl == cur_lbl:                                   continue                                                                                                                                dissolved = (i + 2 < n) and (labels[i + 2] == cur_lbl)                                                                                      # Exit direction from this cluster: price move to the next bar.                                                                             exit_dir = 1 if bars[i + 1]["c"] > bars[i]["c"] else -1
                                                                              # Race condition: destination is a cluster that already has entry_dir.                                                                      # Entry direction wins.                                               if next_lbl > 0 and next_lbl in entry_dir:                                final_dir = entry_dir[next_lbl]                                       kind = "entry_win"                                                else:                                                                     final_dir = exit_dir                                                  kind = "exit"                                                                                                                           # Store entry_dir for the destination cluster on its first visit.                                                                           if next_lbl > 0 and next_lbl not in entry_dir:                            entry_dir[next_lbl] = final_dir                                                                                                         current_dir = final_dir                                                                                                                     signal_events.append({                                                    "bar":       i,                                                       "kind":      kind,                                                    "raw_dir":   exit_dir,                                                "final_dir": final_dir,                                               "confirmed": True,
            "dissolved": dissolved,                                           })                                                                                                                                          if not dissolved:                                                         event_map[i] = final_dir                                                                                                            # ── pass 2: build oscillator ──────────────────────────────────────────────                                                                # Re-entries into a known cluster (from noise or another cluster) replay                                                                    # that cluster's entry_dir immediately, even if no exit event fired.
    osc    = [0] * n                                                      equity = [1.0] * n                                                    pos    = 0                                                                                                                                  prev_lbl = labels[0]                                                  for i in range(n):                                                        cur_lbl = labels[i]                                                                                                                         # Entering a different cluster: apply its entry_dir if known.         if cur_lbl > 0 and cur_lbl != prev_lbl and cur_lbl in entry_dir:                                                                                # Don't double-apply if an event_map entry already covers this bar.                                                                         if i not in event_map:                                                    pos = entry_dir[cur_lbl]                                                                                                            if i in event_map:                                                        pos = event_map[i]                                                                                                                      osc[i]   = pos                                                        prev_lbl = cur_lbl                                                                                                                      # ── equity curve ──────────────────────────────────────────────────────────
    for i in range(1, n):                                                     bar_ret   = (bars[i]["c"] - bars[i - 1]["c"]) / bars[i - 1]["c"]                                                                            equity[i] = equity[i - 1] * (1.0 + osc[i - 1] * bar_ret)                                                                                return labels, osc, equity, signal_events                                                                                               # ── SVG ───────────────────────────────────────────────────────────────────────                                                            # cluster palette (index 0 = noise/grey)                              _CLUSTER_COLORS = [                                                       "#555555",  # 0 noise
    "#ff4444", "#44ff44", "#4488ff", "#ffaa00",                           "#ff44ff", "#00ffff", "#ffff44", "#ff8844",                           "#44ffaa", "#aa44ff", "#44aaff",                                  ]                                                                                                                                           def _cluster_color(label: int) -> str:                                    if label <= 0: return _CLUSTER_COLORS[0]                              return _CLUSTER_COLORS[label % (len(_CLUSTER_COLORS) - 1) + 1]                                                                          def write_svg(bars: List[Dict], labels: List[int], osc: List[int],                  equity: List[float], coin: str,                                       pending_price: Optional[float], current_signal: int,
              fills: List[Dict], live_pos_dir: int = 0, live_pos_usd: float = 0.0,                                                                        pos_history: Optional[List[int]] = None,                              signal_events: Optional[List[Dict]] = None,                           actual_equity: Optional[List[float]] = None):                                                                                     W = 960; ML = 60; MR = 20; MT = 28                                    PRICE_H = 280; OSC_H = 70; EQ_H = 80; ACT_EQ_H = 70; GAP = 22         total_h = MT + PRICE_H + GAP + OSC_H + GAP + EQ_H + GAP + ACT_EQ_H + 28                                                                     plot_w  = W - ML - MR                                             
    now_str = datetime.datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")                                                                         sig_str = "+1 LONG" if current_signal == 1 else ("-1 SHORT" if current_signal == -1 else "FLAT")                                            pending_str = f"  PENDING @ {pending_price:,.4f}" if pending_price else ""                                                                  final_eq = equity[-1] if equity else 1.0                              eq_pct   = (final_eq - 1.0) * 100                                                                                                           svg = [                                                                   '<?xml version="1.0" encoding="UTF-8"?>',                             f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{total_h}">',
        f'<rect width="{W}" height="{total_h}" fill="#0d0d1a"/>',             f'<text x="{W//2}" y="18" text-anchor="middle" '                      f'font-family="Courier New" font-size="11" fill="#cccccc" font-weight="bold">'                                                              f'{coin} DBSCAN-Cluster Bot v5  {now_str}  signal={sig_str}  '
        f'eq={eq_pct:+.2f}%  fills={len(fills)}{pending_str}</text>',     ]                                                                                                                                           n = len(bars)                                                         if n < 2:                                                                 svg.append("</svg>")                                                  _svg_write(coin, svg)                                                 return                                                                                                                                  # x mapping: bar index → pixel                                        def xp(i: int) -> float:                                                  return ML + i / (n - 1) * plot_w
                                                                          # ── price panel ───────────────────────────────────────────────────────────                                                                p_min = min(b["l"] for b in bars)                                     p_max = max(b["h"] for b in bars)                                     p_rng = p_max - p_min or 1.0                                          price_top = MT                                                                                                                              def yp_price(p: float) -> float:                                          return price_top + (1.0 - (p - p_min) / p_rng) * PRICE_H                                                                                # grid lines
    svg.append(f'<rect x="{ML}" y="{price_top}" width="{plot_w}" height="{PRICE_H}" '                                                                      'fill="#0d0d1a" stroke="#ffffff10" stroke-width="0.5"/>')                                                                        for frac in (0.0, 0.25, 0.5, 0.75, 1.0):                                  y = price_top + frac * PRICE_H                                        price_label = p_max - frac * p_rng                                    svg.append(f'<line x1="{ML}" x2="{W-MR}" y1="{y:.1f}" y2="{y:.1f}" '                                                                                   'stroke="#ffffff12" stroke-width="0.5"/>')                 svg.append(f'<text x="{ML-3}" y="{y+3:.1f}" text-anchor="end" '
                   f'font-family="Courier New" font-size="7" fill="#888">'                                                                                     f'{price_label:,.1f}</text>')                                                                                                # candles coloured by cluster                                         bw = max(0.8, plot_w / n * 0.7)                                       for i, b in enumerate(bars):                                              x   = xp(i)                                                           clr = _cluster_color(labels[i] if i < len(labels) else 0)             yh  = yp_price(b["h"]); yl  = yp_price(b["l"])                        yo  = yp_price(b["o"]); yc  = yp_price(b["c"])                        fill = clr if b["c"] >= b["o"] else "#0d0d1a"
        # wick                                                                svg.append(f'<line x1="{x:.1f}" y1="{yh:.1f}" x2="{x:.1f}" y2="{yl:.1f}" '                                                                             f'stroke="{clr}" stroke-width="0.5"/>')                    top = min(yo, yc); bot = max(yo, yc, top + 0.5)                       svg.append(f'<rect x="{x - bw/2:.1f}" y="{top:.1f}" width="{bw:.1f}" '                                                                                 f'height="{bot - top:.1f}" fill="{fill}" stroke="{clr}" stroke-width="0.3"/>')                                                                                                                     # pending order line                                                  if pending_price is not None and p_min <= pending_price <= p_max:
        ypp = yp_price(pending_price)                                         svg.append(f'<line x1="{ML}" x2="{W-MR}" y1="{ypp:.1f}" y2="{ypp:.1f}" '                                                                               'stroke="#f5a623" stroke-width="1" stroke-dasharray="4,3"/>')                                                                    svg.append(f'<text x="{W-MR-4}" y="{ypp-3:.1f}" text-anchor="end" '                                                                                    'font-family="Courier New" font-size="8" fill="#f5a623">'                                                                                   f'limit {pending_price:,.4f}</text>')                                                                                        # fill ticks — small triangles/marks BELOW the price panel (not inside it)                                                                  tick_y = price_top + PRICE_H + 3   # just below price panel           for ev in fills:                                                          bi = min(range(n), key=lambda k: abs(bars[k]["t"] - ev["t"]))         bx = xp(bi)                                                           clr = "#44ff44" if ev["dir"] == 1 else "#ff4444"                      # small upward or downward triangle                                   if ev["dir"] == 1:                                                        svg.append(f'<polygon points="{bx:.1f},{tick_y} {bx-4:.1f},{tick_y+8} '                                                                                f'{bx+4:.1f},{tick_y+8}" fill="{clr}" opacity="0.85"/>')
        else:                                                                     svg.append(f'<polygon points="{bx:.1f},{tick_y+8} {bx-4:.1f},{tick_y} '                                                                                f'{bx+4:.1f},{tick_y}" fill="{clr}" opacity="0.85"/>')                                                                                                                                         svg.append(f'<text x="{ML+4}" y="{price_top+12}" font-family="Courier New" '                                                                           'font-size="9" fill="#aaa">PRICE (1m · last 3000 bars · DBSCAN clusters)</text>')                                                                                                                      # ── position size label ABOVE oscillator (white, outside panel) ──────────                                                                 osc_top = price_top + PRICE_H + GAP                                   osc_mid = osc_top + OSC_H / 2                                                                                                               if live_pos_dir == 1:                                                     pos_label_color = "#44ff44"                                           pos_label_str   = f"LONG  ${live_pos_usd:,.1f}"                   elif live_pos_dir == -1:                                                  pos_label_color = "#ff4444"                                           pos_label_str   = f"SHORT ${live_pos_usd:,.1f}"                   else:                                                                     pos_label_color = "#ffffff"
        pos_label_str   = "FLAT"                                                                                                                svg.append(f'<text x="{W//2}" y="{osc_top - 6}" text-anchor="middle" '                                                                                 f'font-family="Courier New" font-size="10" font-weight="bold" fill="#ffffff">'                                                              f'Position: {pos_label_str}</text>')                                                                                             # ── oscillator panel ──────────────────────────────────────────────────────                                                                svg.append(f'<rect x="{ML}" y="{osc_top}" width="{plot_w}" height="{OSC_H}" '
               'fill="#0a0a15" stroke="#ffffff10" stroke-width="0.5"/>')                                                                        svg.append(f'<line x1="{ML}" x2="{W-MR}" y1="{osc_mid:.1f}" y2="{osc_mid:.1f}" '                                                                       'stroke="#ffffff22" stroke-width="0.5"/>')                 svg.append(f'<text x="{ML-3}" y="{osc_top+9}" text-anchor="end" '                'font-family="Courier New" font-size="7" fill="#44ff44">+1</text>')                                                              svg.append(f'<text x="{ML-3}" y="{osc_top+OSC_H}" text-anchor="end" '                                                                                  'font-family="Courier New" font-size="7" fill="#ff4444">-1</text>')
                                                                          for i, sig in enumerate(osc):                                             if sig == 0: continue                                                 x = xp(i)                                                             if sig > 0:                                                               svg.append(f'<line x1="{x:.1f}" y1="{osc_top+2:.1f}" x2="{x:.1f}" y2="{osc_mid:.1f}" '                                                                 'stroke="#44ff4488" stroke-width="0.9"/>')             else:                                                                     svg.append(f'<line x1="{x:.1f}" y1="{osc_mid:.1f}" x2="{x:.1f}" '                                                                                      f'y2="{osc_top+OSC_H-2:.1f}" stroke="#ff444488" stroke-width="0.9"/>')                                                                                                                         # ── signal event vertical lines on oscillator ────────────────────────────                                                                 # exit      → yellow (long) / pink (short)                            # entry_win → cyan  (long) / orange (short)  [race: entry_dir beat exit_dir]                                                                # dissolved → dashed                                                  if signal_events:                                                         for ev in signal_events:                                                  ex   = xp(ev["bar"])                                                  kind = ev.get("kind", "exit")
            if kind == "entry_win":                                                   ev_clr = "#00ffee" if ev["final_dir"] == 1 else "#ff8800"                                                                               else:                                                                     ev_clr = "#ffee44" if ev["final_dir"] == 1 else "#ff44aa"                                                                               dash = 'stroke-dasharray="3,3"' if ev["dissolved"] else ""            svg.append(f'<line x1="{ex:.1f}" y1="{osc_top:.1f}" x2="{ex:.1f}" '                                                                                    f'y2="{osc_top+OSC_H:.1f}" stroke="{ev_clr}" stroke-width="1.2" '                                                                           f'opacity="0.75" {dash}/>')
                                                                          # ── exchange position history line (WHITE) ────────────────────────────────                                                                def _osc_y_for_pos(p: int) -> float:                                      if p == 1:  return osc_top + OSC_H * 0.12                             if p == -1: return osc_top + OSC_H * 0.88                             return osc_mid                                                                                                                          if pos_history and len(pos_history) >= 2:                                 ph = pos_history[-n:] if len(pos_history) > n else pos_history        pad = n - len(ph)                                                     ph = [0] * pad + list(ph)
        pts = " ".join(f"{xp(i):.1f},{_osc_y_for_pos(ph[i]):.1f}" for i in range(n))                                                                svg.append(f'<polyline points="{pts}" fill="none" '                              'stroke="#ffffff" stroke-width="1.2" stroke-linejoin="round" '                                                                              'stroke-linecap="round" opacity="0.85"/>')                                                                                   svg.append(f'<text x="{ML+4}" y="{osc_top+10}" font-family="Courier New" '                                                                             f'font-size="9" fill="#aaa">SIGNAL (+1 long · -1 short)</text>')                                                             
    # ── theoretical equity panel ──────────────────────────────────────────────                                                                eq_top = osc_top + OSC_H + GAP                                        eq_min = min(equity); eq_max = max(equity)                            eq_rng = eq_max - eq_min or 1e-9                                                                                                            def yp_eq(v: float) -> float:                                             return eq_top + (1.0 - (v - eq_min) / eq_rng) * (EQ_H - 4) + 2                                                                          svg.append(f'<rect x="{ML}" y="{eq_top}" width="{plot_w}" height="{EQ_H}" '                                                                            'fill="#0a0a15" stroke="#ffffff10" stroke-width="0.5"/>')                                                                        svg.append(f'<line x1="{ML}" x2="{W-MR}" y1="{yp_eq(1.0):.1f}" y2="{yp_eq(1.0):.1f}" '                                                                 'stroke="#ffffff22" stroke-width="0.5"/>')                                                                                       coords = " ".join(f"{xp(i):.1f},{yp_eq(equity[i]):.1f}" for i in range(n))                                                                  eq_color = "#44ff44" if final_eq >= 1.0 else "#ff4444"                svg.append(f'<polyline points="{coords}" fill="none" stroke="{eq_color}" '                                                                             'stroke-width="1.2" stroke-linejoin="round"/>')        
    svg.append(f'<text x="{W-MR-3}" y="{eq_top+11}" text-anchor="end" '                                                                                    f'font-family="Courier New" font-size="9" fill="{eq_color}">'                                                                               f'{eq_pct:+.2f}%</text>')                                  svg.append(f'<text x="{ML+4}" y="{eq_top+10}" font-family="Courier New" '                                                                              'font-size="9" fill="#aaa">THEORETICAL EQUITY (unit size)</text>')                                                                                                                                     # ── actual equity panel (position-size weighted) ──────────────────────────
    act_top = eq_top + EQ_H + GAP                                         if actual_equity and len(actual_equity) >= 2:                             ae = actual_equity                                                else:                                                                     ae = [1.0] * n   # fallback flat line if no data yet                                                                                    ae_min = min(ae); ae_max = max(ae)                                    ae_rng = ae_max - ae_min or 1e-9                                                                                                            def yp_ae(v: float) -> float:                                             return act_top + (1.0 - (v - ae_min) / ae_rng) * (ACT_EQ_H - 4) + 2

    svg.append(f'<rect x="{ML}" y="{act_top}" width="{plot_w}" height="{ACT_EQ_H}" '                                                                       'fill="#0a0a15" stroke="#ffffff10" stroke-width="0.5"/>')                                                                        svg.append(f'<line x1="{ML}" x2="{W-MR}" y1="{yp_ae(1.0):.1f}" y2="{yp_ae(1.0):.1f}" '                                                                 'stroke="#ffffff22" stroke-width="0.5"/>')                                                                                       ae_coords = " ".join(f"{xp(i):.1f},{yp_ae(ae[i]):.1f}" for i in range(min(n, len(ae))))
    final_ae = ae[-1] if ae else 1.0                                      ae_pct   = (final_ae - 1.0) * 100                                     ae_color = "#44aaff" if final_ae >= 1.0 else "#ff8844"                svg.append(f'<polyline points="{ae_coords}" fill="none" stroke="{ae_color}" '                                                                          'stroke-width="1.2" stroke-linejoin="round"/>')                                                                                  svg.append(f'<text x="{W-MR-3}" y="{act_top+11}" text-anchor="end" '                                                                                   f'font-family="Courier New" font-size="9" fill="{ae_color}">'                                                                               f'{ae_pct:+.2f}%</text>')
    svg.append(f'<text x="{ML+4}" y="{act_top+10}" font-family="Courier New" '                                                                             'font-size="9" fill="#aaa">ACTUAL EQUITY (by position size)</text>')                                                                                                                                   # ── legend ────────────────────────────────────────────────────────────────                                                                ly2 = total_h - 10                                                    items = [("#44ff44", "none",  "signal+1"),                                     ("#ff4444", "none",  "signal-1"),                                     ("#f5a623", "4,3",   "limit"),                                        ("#aaaaaa", "none",  "noise"),
             ("#ffffff", "none",  "exch.pos"),                                     ("#ffee44", "none",  "exit↑"),                                        ("#ff44aa", "none",  "exit↓"),                                        ("#00ffee", "none",  "entry↑win"),                                    ("#ff8800", "none",  "entry↓win"),                       ]                                                                         lx2 = ML                                                              for lc, ld, lt in items:                                                  dash = f' stroke-dasharray="{ld}"' if ld != "none" else ""            svg.append(f'<line x1="{lx2}" x2="{lx2+12}" y1="{ly2}" y2="{ly2}" '                                                                                    f'stroke="{lc}" stroke-width="1.5"{dash}/>')
        svg.append(f'<text x="{lx2+15}" y="{ly2+4}" font-family="Courier New" '                                                                                f'font-size="8" fill="{lc}">{lt}</text>')                  lx2 += 80                                                         # cluster colour swatches                                             for ci in range(1, 6):                                                    c = _CLUSTER_COLORS[ci]                                               svg.append(f'<rect x="{lx2}" y="{ly2-5}" width="8" height="8" fill="{c}"/>')                                                                svg.append(f'<text x="{lx2+10}" y="{ly2+3}" font-family="Courier New" '                                                                                f'font-size="8" fill="{c}">C{ci}</text>')
        lx2 += 38                                                                                                                               svg.append("</svg>")                                                  _svg_write(coin, svg)                                                                                                                                                                                         def _svg_write(coin: str, lines: List[str]):                              fname = f"{coin}.svg"; tmp = f"{fname}.{os.getpid()}.tmp"             with open(tmp, "w") as f: f.write("\n".join(lines))                   os.replace(tmp, fname)                                                                                                                  # ── main ──────────────────────────────────────────────────────────────────────                                                            import argparse                                                                                                                             def main():                                                               global SYMBOL, SYM, AMT_USD, LEVERAGE                                                                                                       parser = argparse.ArgumentParser(description="DBSCAN Cluster Bot v5")                                                                       parser.add_argument("coin",    type=str,   help="Coin symbol (e.g. BTC, ETH, SOL, DOGE …)")                                                 parser.add_argument("dollars", type=float, help="Position size in USD per trade")
    parser.add_argument("--lev",   type=int,   default=10, help="Leverage (default: 10)")                                                       args = parser.parse_args()                                                                                                                  coin     = args.coin.upper()                                          AMT_USD  = args.dollars                                               LEVERAGE = args.lev                                                                                                                         cfg    = _coin_cfg(coin)                                              SYMBOL = cfg["binance"]                                               SYM    = cfg["mexc"]                                              
    if not MEXC_KEY or not MEXC_SECRET:                                       log.error("MEXC / MEXCSECRET env vars not set"); sys.exit(1)                                                                            load_specs()                                                          if SYM not in specs:                                                      log.error(f"{SYM} not in MEXC specs"); sys.exit(1)                                                                                      # ── state ─────────────────────────────────────────────────────────────────                                                                pending_oid:   Optional[str]   = None                                 pending_price: Optional[float] = None                                 pending_dir:   int             = 0     # direction of the pending/open order (+1 or -1)                                                     fills:         List[Dict]      = []    # filled orders for SVG dots                                                                         cycle:         int             = 0                                    # Exchange position sampled every minute — aligned to bar count for SVG line.                                                               # Each element is the live_pos_dir observed that cycle: +1, -1, or 0.                                                                       pos_history:   List[int]       = []                                   # Actual equity tracking: cumulative product of bar returns weighted by                                                                     # actual position size (in USD) at the time of each bar.
    actual_equity: List[float]     = [1.0]                                # Track whether we already placed a delta-correction this cycle to avoid                                                                    # placing multiple corrective orders before the first one fills.      delta_pending_oid:   Optional[str] = None                             delta_pending_dir:   int           = 0                                                                                                      log.info(f"DBSCAN bot started  coin={coin}  size=${AMT_USD}  lev={LEVERAGE}x")                                                                                                                                    # Sync last_signal from actual exchange position so we don't          # double-enter a position that already exists from a previous run.
    _boot_dir, _boot_usd = get_position()                                 last_signal: Optional[int] = _boot_dir if _boot_dir != 0 else None    log.info(f"Boot position: dir={_boot_dir:+d}  usd=${_boot_usd:.2f}  "                                                                                f"→ last_signal initialised to {last_signal}")                                                                                     # initial SVG before first tick                                       try:                                                                      bars = fetch_1m_candles()                                             labels, osc, equity, signal_events = compute_signals(bars)            write_svg(bars, labels, osc, equity, coin, pending_price,                       osc[-1] if osc else 0, fills, live_pos_dir=0, live_pos_usd=0.0,                                                                             pos_history=pos_history, signal_events=signal_events,                                                                                       actual_equity=None)                                         log.info(f"Initial SVG written  bars={len(bars)}  "                            f"clusters={len(set(l for l in labels if l > 0))}")      except Exception as e:                                                    log.warning(f"initial SVG failed: {e}", exc_info=True)                                                                                  # ── minute loop ───────────────────────────────────────────────────────────                                                                while True:
        now  = time.time()                                                    wake = (int(now) // 60 + 1) * 60 + 1   # next minute + 1 s            time.sleep(max(0, wake - now))                                        cycle += 1                                                                                                                                  try:                                                                      now_ms = int(time.time() * 1000)                                                                                                            # 1. fetch candles & recompute DBSCAN each cycle                      bars = fetch_1m_candles()                                             if len(bars) < 10:                                                        log.warning(f"[{cycle}] too few bars ({len(bars)})")
                continue                                                          labels, osc, equity, signal_events = compute_signals(bars)            current_signal = osc[-1] if osc else 0                                n_clusters = len(set(l for l in labels if l > 0))                     mark = get_mark()                                                     live_pos_dir, live_pos_usd = get_position()                                                                                                 # Record live exchange position each cycle for the SVG line.                                                                                pos_history.append(live_pos_dir)                                                                                                            # Update actual equity: append one bar weighted by live position size.                                                                      # We track it as a multiplier series. USD P&L per bar ≈               # bar_ret * live_pos_dir * live_pos_usd, expressed as fraction of                                                                           # initial AMT_USD so the curve starts at 1.0 and grows/shrinks.                                                                             if len(bars) >= 2:                                                        bar_ret = (bars[-1]["c"] - bars[-2]["c"]) / bars[-2]["c"]                                                                                   size_frac = (live_pos_usd / AMT_USD) if AMT_USD > 0 else 0.0                                                                                prev_ae = actual_equity[-1] if actual_equity else 1.0
                actual_equity.append(prev_ae * (1.0 + live_pos_dir * size_frac * bar_ret))                                                                                                                                    last_str = f"{last_signal:+d}" if last_signal is not None else "none"                                                                       log.info(f"[{cycle}] bars={len(bars)}  clusters={n_clusters}  "                                                                                      f"signal={current_signal:+d}  last_acted={last_str}  "                                                                                      f"mark={mark:.4f}  pos={live_pos_dir:+d} ${live_pos_usd:.1f}  eq={((equity[-1]-1)*100):+.2f}%")                        
            # 2. check pending fill (strategy order)                              if pending_oid is not None:                                               if is_filled(pending_oid):                                                log.info(f"[{cycle}] FILLED id={pending_oid} @ {pending_price:.4f}  dir={pending_dir:+d}")                                                  fills.append({"t": now_ms, "price": pending_price, "dir": pending_dir})                                                                     pending_oid   = None                                                  pending_price = None                                                  # pending_dir stays — reflects the live position direction                                                                              else:                                                                     log.info(f"[{cycle}] waiting fill  id={pending_oid} @ {pending_price:.4f}")
                    # signal flipped while order pending: cancel and let the                                                                                    # transition block below immediately reopen the other side                                                                                  if current_signal != last_signal:                                         log.info(f"[{cycle}] signal flipped while pending — cancelling {pending_oid}")                                                              cancel_order(pending_oid)                                             pending_oid   = None
                        pending_price = None                                                  last_signal   = None  # force re-trigger below this cycle                                                                               else:                                                                     write_svg(bars, labels, osc, equity, coin,                                  pending_price, current_signal, fills,                                 live_pos_dir=live_pos_dir, live_pos_usd=live_pos_usd,                                                                                       pos_history=pos_history, signal_events=signal_events,
                              actual_equity=actual_equity)                                    continue                                                                                                                        # 2b. check pending delta-correction fill                             if delta_pending_oid is not None:
                if is_filled(delta_pending_oid):
                    log.info(f"[{cycle}] DELTA FILLED id={delta_pending_oid}  dir={delta_pending_dir:+d}")                                                      delta_pending_oid = None                                              delta_pending_dir = 0                                             else:
                    log.info(f"[{cycle}] waiting delta-correction fill  id={delta_pending_oid}")                                                                                                                              # 3. delta correction — reconcile exchange position with internal state.                                                                    # internal_dir: what this bot session believes the position should be.                                                                      # If no strategy order pending and no delta order pending, and the
            # exchange disagrees by a full side flip (or unexpected flat), correct it.                                                                  internal_dir = last_signal if last_signal is not None else 0                                                                                delta = live_pos_dir - internal_dir  # e.g. +2 means exch=+1 when we expect -1
            meaningful_delta = (delta != 0 and                                                        pending_oid is None and                                               delta_pending_oid is None)                        if meaningful_delta:                                                      # Target is internal_dir; place corrective order toward it.                                                                                 # If internal_dir is 0 (flat), close whatever is open (use opposite side).                                                                  if internal_dir == 0:                                                     # Close the unexpected position: place opposing limit to flatten.                                                                           correct_dir = -live_pos_dir   # flip to close                     else:                                                                     correct_dir = internal_dir    # re-assert the intended side                                                                             log.warning(f"[{cycle}] DELTA CORRECTION  exch={live_pos_dir:+d}  "                                                                                     f"internal={internal_dir:+d}  delta={delta:+d}  "
                            f"→ placing corrective order dir={correct_dir:+d}")                                                                             oid = place_limit_order(correct_dir, mark)                            if oid:                                                                   delta_pending_oid = oid                                               delta_pending_dir = correct_dir                                                                                                     # 4. act on signal transitions                                        # In hedge mode we must explicitly close the old side then open
            # the new one.  We send both orders back-to-back at mark price;                                                                             # they fill at taker speed.                                           if current_signal != 0 and current_signal != last_signal:
                direction = current_signal                                            label = "LONG" if direction == 1 else "SHORT"                                                                                               # Guard: exchange already holds the right side → just sync.                                                                                 if live_pos_dir == direction:                                             log.info(f"[{cycle}] → {label} already on exchange "                                                                                                 f"(${live_pos_usd:.1f}) — syncing, no new order")
                    last_signal = current_signal                                      else:                                                                     log.info(f"[{cycle}] → {label}  mark={mark:.4f}")                     last_signal = current_signal                      
                    # Step 1: close the existing opposite position if open.                                                                                     if live_pos_dir != 0 and live_pos_dir != direction:                                                                                             log.info(f"[{cycle}]   closing opposite side dir={live_pos_dir:+d}")
                        close_position(live_pos_dir, mark)                                                                                                      # Step 2: open the new side.                                          oid = place_limit_order(direction, mark)                              if oid:                                                                   pending_oid   = oid                                                   pending_price = mark                                                  pending_dir   = direction                     
            # 5. write SVG every cycle
            write_svg(bars, labels, osc, equity, coin,                                      pending_price, current_signal, fills,                                 live_pos_dir=live_pos_dir, live_pos_usd=live_pos_usd,                                                                                       pos_history=pos_history, signal_events=signal_events,                                                                                       actual_equity=actual_equity)                                                                                                  except Exception as e:                                                    log.warning(f"[{cycle}] {e}", exc_info=True)
                                                                                                                                            if __name__ == "__main__":                                                main()